sequelize model:create --name Account --attributes status:enum
sequelize model:create --name User --attributes status:enum
sequelize model:create --name Admin --attributes status:enum
sequelize model:create --name SuperAdmin --attributes status:enum
sequelize model:create --name Sport --attributes status:enum
sequelize model:create --name UserSport --attributes status:enum
sequelize model:create --name UserSportGroup --attributes status:enum
sequelize model:create --name UserSportGroupCompetitor --attributes status:enum
sequelize model:create --name UserSportGroupPlayer --attributes status:enum
sequelize model:create --name UserSportGroupTeam --attributes status:enum
sequelize model:create --name UserSportGroupTeamPlayer --attributes status:enum
sequelize model:create --name AdminSport --attributes status:enum
sequelize model:create --name Structure --attributes status:enum
sequelize model:create --name OficialStructure --attributes status:enum
sequelize model:create --name UserStructure --attributes status:enum
sequelize model:create --name Tournament --attributes status:enum
sequelize model:create --name Stage --attributes status:enum
sequelize model:create --name StageGroup --attributes status:enum
sequelize model:create --name StageGroupCompetitor --attributes status:enum
sequelize model:create --name Match --attributes status:enum
sequelize model:create --name MatchCompetitor --attributes status:enum
